### ISSUE TITLE
Exception received: ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by georf** [aerobounce/Sublime-Pretty-Shell#1]
I use the default settings with a fresh plugin installed and got the following error:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/home/georf/.config/sublime-text-3/Installed Packages/Pretty Shell.sublime-package/PrettyShell.py", line 190, in run
  File "/home/georf/.config/sublime-text-3/Installed Packages/Pretty Shell.sublime-package/PrettyShell.py", line 185, in shfmt
  File "/home/georf/.config/sublime-text-3/Installed Packages/Pretty Shell.sublime-package/PrettyShell.py", line 162, in format_text
  File "/home/georf/.config/sublime-text-3/Installed Packages/Pretty Shell.sublime-package/PrettyShell.py", line 70, in update_phantoms
ValueError: invalid literal for int() with base 10: ''
```

**Comment by aerobounce** [comment]
You need to specify absolute path to `shfmt` in settings.
> "shfmt_bin_path": "Absolute Path to shfmt"

If you've already done that, provide your environments please.

**Comment by georf** [comment]
Okay, that was it.

Thanks for this plugin!
